version: '3.7'

services:
  discord-bot:
    container_name: discord-bot
    image: zkey-coordinator-discord
    build: .
    restart: always
    command: start

  discord-redis:
    container_name: discord-redis
    image: redis
    restart: always
    volumes:
      - ./redis/data:/data

  discord-init:
    container_name: discord-init
    image: zkey-coordinator-discord
    depends_on:
      - discord-bot
    restart: never
    command: deploy-commands